apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  DB_URL: "jdbc:postgresql://postgres-service.data.svc.cluster.local:5432/techsalary"
  DB_USER: "techsalary"
  DB_HOST: "postgres-service.data.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "techsalary"
  IDENTITY_SERVICE_URL: "http://identity-service.app.svc.cluster.local:8081"
  SALARY_SERVICE_URL: "http://salary-service.app.svc.cluster.local:8082"
  VOTE_SERVICE_URL: "http://vote-service.app.svc.cluster.local:8083"
  SEARCH_SERVICE_URL: "http://search-service.app.svc.cluster.local:8084"
  STATS_SERVICE_URL: "http://stats-service.app.svc.cluster.local:8085"
