apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
stringData:
  DB_PASSWORD: "techsalary_pass"
  INTERNAL_SERVICE_TOKEN: "internal-secret-token-change-in-prod"
  JWT_SECRET: "mysecretkey12345678901234567890ab"
