spring.application.name=salary-service
server.port=8082

# DB  values injected from K8s ConfigMap/Secret
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/techsalary}
spring.datasource.username=${DB_USER:techsalary}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=salary
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Actuator for K8s liveness/readiness probes
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# for local dev
#spring.application.name=salary-service
#server.port=8082
#
#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/techsalary}
#spring.datasource.username=${DB_USER:techsalary}
#spring.datasource.password=${DB_PASSWORD:techsalary_pass}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.connection-timeout=30000
#
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.default_schema=salary
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#management.endpoints.web.exposure.include=health,info
#management.endpoint.health.show-details=never